/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ApiPublicSettingsRouteImport } from './routes/api/public/settings'
import { Route as ApiPublicPaypalCallbackRouteImport } from './routes/api/public/paypal-callback'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/_app/referrals'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/_app/orders'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppCheckoutRouteImport } from './routes/_authenticated/_app/checkout'
import { Route as AuthenticatedAppBooksIndexRouteImport } from './routes/_authenticated/_app/books.index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicWebhooksGatewayRouteImport } from './routes/api/public/webhooks/$gateway'
import { Route as ApiPublicBlogImagesSplatRouteImport } from './routes/api/public/blog-images/$'
import { Route as AuthenticatedAppCheckoutSuccessRouteImport } from './routes/_authenticated/_app/checkout.success'
import { Route as AuthenticatedAppCheckoutCancelRouteImport } from './routes/_authenticated/_app/checkout.cancel'
import { Route as AuthenticatedAppBooksNewRouteImport } from './routes/_authenticated/_app/books.new'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin.settings'
import { Route as AuthenticatedAdminAdminReferralsRouteImport } from './routes/_authenticated/_admin/admin.referrals'
import { Route as AuthenticatedAdminAdminPlansRouteImport } from './routes/_authenticated/_admin/admin.plans'
import { Route as AuthenticatedAdminAdminPaymentGatewaysRouteImport } from './routes/_authenticated/_admin/admin.payment-gateways'
import { Route as AuthenticatedAdminAdminOrdersRouteImport } from './routes/_authenticated/_admin/admin.orders'
import { Route as AuthenticatedAdminAdminMessagesRouteImport } from './routes/_authenticated/_admin/admin.messages'
import { Route as AuthenticatedAdminAdminEmailTemplatesRouteImport } from './routes/_authenticated/_admin/admin.email-templates'
import { Route as AuthenticatedAdminAdminEmailLogsRouteImport } from './routes/_authenticated/_admin/admin.email-logs'
import { Route as AuthenticatedAdminAdminCouponsRouteImport } from './routes/_authenticated/_admin/admin.coupons'
import { Route as AuthenticatedAdminAdminCacheRouteImport } from './routes/_authenticated/_admin/admin.cache'
import { Route as AuthenticatedAdminAdminBooksRouteImport } from './routes/_authenticated/_admin/admin.books'
import { Route as AuthenticatedAdminAdminAnalyticsRouteImport } from './routes/_authenticated/_admin/admin.analytics'
import { Route as AuthenticatedAdminAdminAiRoutingRouteImport } from './routes/_authenticated/_admin/admin.ai-routing'
import { Route as AuthenticatedAdminAdminAiProvidersRouteImport } from './routes/_authenticated/_admin/admin.ai-providers'
import { Route as AuthenticatedAdminAdminAiPromptsRouteImport } from './routes/_authenticated/_admin/admin.ai-prompts'
import { Route as AuthenticatedAdminAdminAiModelsRouteImport } from './routes/_authenticated/_admin/admin.ai-models'
import { Route as AuthenticatedAdminAdminAiLogsRouteImport } from './routes/_authenticated/_admin/admin.ai-logs'
import { Route as AuthenticatedAdminAdminAiLimitsRouteImport } from './routes/_authenticated/_admin/admin.ai-limits'
import { Route as AuthenticatedAdminAdminAiHealthRouteImport } from './routes/_authenticated/_admin/admin.ai-health'
import { Route as AuthenticatedAdminAdminAiFeaturesRouteImport } from './routes/_authenticated/_admin/admin.ai-features'
import { Route as AuthenticatedAdminAdminAiFallbackRouteImport } from './routes/_authenticated/_admin/admin.ai-fallback'
import { Route as AuthenticatedAdminAdminAiCostsRouteImport } from './routes/_authenticated/_admin/admin.ai-costs'
import { Route as AuthenticatedAdminAdminAiAuditRouteImport } from './routes/_authenticated/_admin/admin.ai-audit'
import { Route as AuthenticatedAppBooksBookIdIndexRouteImport } from './routes/_authenticated/_app/books.$bookId.index'
import { Route as AuthenticatedAdminAdminBlogIndexRouteImport } from './routes/_authenticated/_admin/admin.blog.index'
import { Route as AuthenticatedAppBooksBookIdPreviewRouteImport } from './routes/_authenticated/_app/books.$bookId.preview'
import { Route as AuthenticatedAppBooksBookIdPhotosRouteImport } from './routes/_authenticated/_app/books.$bookId.photos'
import { Route as AuthenticatedAppBooksBookIdManuscriptRouteImport } from './routes/_authenticated/_app/books.$bookId.manuscript'
import { Route as AuthenticatedAppBooksBookIdInterviewRouteImport } from './routes/_authenticated/_app/books.$bookId.interview'
import { Route as AuthenticatedAdminAdminBlogNewRouteImport } from './routes/_authenticated/_admin/admin.blog.new'
import { Route as AuthenticatedAdminAdminBlogPostIdRouteImport } from './routes/_authenticated/_admin/admin.blog.$postId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSettingsRoute = ApiPublicSettingsRouteImport.update({
  id: '/api/public/settings',
  path: '/api/public/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalCallbackRoute = ApiPublicPaypalCallbackRouteImport.update({
  id: '/api/public/paypal-callback',
  path: '/api/public/paypal-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCheckoutRoute =
  AuthenticatedAppCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBooksIndexRoute =
  AuthenticatedAppBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksGatewayRoute =
  ApiPublicWebhooksGatewayRouteImport.update({
    id: '/api/public/webhooks/$gateway',
    path: '/api/public/webhooks/$gateway',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlogImagesSplatRoute =
  ApiPublicBlogImagesSplatRouteImport.update({
    id: '/api/public/blog-images/$',
    path: '/api/public/blog-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppCheckoutSuccessRoute =
  AuthenticatedAppCheckoutSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedAppCheckoutRoute,
  } as any)
const AuthenticatedAppCheckoutCancelRoute =
  AuthenticatedAppCheckoutCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => AuthenticatedAppCheckoutRoute,
  } as any)
const AuthenticatedAppBooksNewRoute =
  AuthenticatedAppBooksNewRouteImport.update({
    id: '/books/new',
    path: '/books/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminReferralsRoute =
  AuthenticatedAdminAdminReferralsRouteImport.update({
    id: '/admin/referrals',
    path: '/admin/referrals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminPlansRoute =
  AuthenticatedAdminAdminPlansRouteImport.update({
    id: '/admin/plans',
    path: '/admin/plans',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminPaymentGatewaysRoute =
  AuthenticatedAdminAdminPaymentGatewaysRouteImport.update({
    id: '/admin/payment-gateways',
    path: '/admin/payment-gateways',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrdersRoute =
  AuthenticatedAdminAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminMessagesRoute =
  AuthenticatedAdminAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminEmailTemplatesRoute =
  AuthenticatedAdminAdminEmailTemplatesRouteImport.update({
    id: '/admin/email-templates',
    path: '/admin/email-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminEmailLogsRoute =
  AuthenticatedAdminAdminEmailLogsRouteImport.update({
    id: '/admin/email-logs',
    path: '/admin/email-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminCouponsRoute =
  AuthenticatedAdminAdminCouponsRouteImport.update({
    id: '/admin/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminCacheRoute =
  AuthenticatedAdminAdminCacheRouteImport.update({
    id: '/admin/cache',
    path: '/admin/cache',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBooksRoute =
  AuthenticatedAdminAdminBooksRouteImport.update({
    id: '/admin/books',
    path: '/admin/books',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnalyticsRoute =
  AuthenticatedAdminAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiRoutingRoute =
  AuthenticatedAdminAdminAiRoutingRouteImport.update({
    id: '/admin/ai-routing',
    path: '/admin/ai-routing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiProvidersRoute =
  AuthenticatedAdminAdminAiProvidersRouteImport.update({
    id: '/admin/ai-providers',
    path: '/admin/ai-providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiPromptsRoute =
  AuthenticatedAdminAdminAiPromptsRouteImport.update({
    id: '/admin/ai-prompts',
    path: '/admin/ai-prompts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiModelsRoute =
  AuthenticatedAdminAdminAiModelsRouteImport.update({
    id: '/admin/ai-models',
    path: '/admin/ai-models',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiLogsRoute =
  AuthenticatedAdminAdminAiLogsRouteImport.update({
    id: '/admin/ai-logs',
    path: '/admin/ai-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiLimitsRoute =
  AuthenticatedAdminAdminAiLimitsRouteImport.update({
    id: '/admin/ai-limits',
    path: '/admin/ai-limits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiHealthRoute =
  AuthenticatedAdminAdminAiHealthRouteImport.update({
    id: '/admin/ai-health',
    path: '/admin/ai-health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiFeaturesRoute =
  AuthenticatedAdminAdminAiFeaturesRouteImport.update({
    id: '/admin/ai-features',
    path: '/admin/ai-features',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiFallbackRoute =
  AuthenticatedAdminAdminAiFallbackRouteImport.update({
    id: '/admin/ai-fallback',
    path: '/admin/ai-fallback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiCostsRoute =
  AuthenticatedAdminAdminAiCostsRouteImport.update({
    id: '/admin/ai-costs',
    path: '/admin/ai-costs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiAuditRoute =
  AuthenticatedAdminAdminAiAuditRouteImport.update({
    id: '/admin/ai-audit',
    path: '/admin/ai-audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppBooksBookIdIndexRoute =
  AuthenticatedAppBooksBookIdIndexRouteImport.update({
    id: '/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminBlogIndexRoute =
  AuthenticatedAdminAdminBlogIndexRouteImport.update({
    id: '/admin/blog/',
    path: '/admin/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppBooksBookIdPreviewRoute =
  AuthenticatedAppBooksBookIdPreviewRouteImport.update({
    id: '/books/$bookId/preview',
    path: '/books/$bookId/preview',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBooksBookIdPhotosRoute =
  AuthenticatedAppBooksBookIdPhotosRouteImport.update({
    id: '/books/$bookId/photos',
    path: '/books/$bookId/photos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBooksBookIdManuscriptRoute =
  AuthenticatedAppBooksBookIdManuscriptRouteImport.update({
    id: '/books/$bookId/manuscript',
    path: '/books/$bookId/manuscript',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBooksBookIdInterviewRoute =
  AuthenticatedAppBooksBookIdInterviewRouteImport.update({
    id: '/books/$bookId/interview',
    path: '/books/$bookId/interview',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminBlogNewRoute =
  AuthenticatedAdminAdminBlogNewRouteImport.update({
    id: '/admin/blog/new',
    path: '/admin/blog/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBlogPostIdRoute =
  AuthenticatedAdminAdminBlogPostIdRouteImport.update({
    id: '/admin/blog/$postId',
    path: '/admin/blog/$postId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout': typeof AuthenticatedAppCheckoutRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/orders': typeof AuthenticatedAppOrdersRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/referrals': typeof AuthenticatedAppReferralsRoute
  '/api/public/paypal-callback': typeof ApiPublicPaypalCallbackRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/admin/ai-audit': typeof AuthenticatedAdminAdminAiAuditRoute
  '/admin/ai-costs': typeof AuthenticatedAdminAdminAiCostsRoute
  '/admin/ai-fallback': typeof AuthenticatedAdminAdminAiFallbackRoute
  '/admin/ai-features': typeof AuthenticatedAdminAdminAiFeaturesRoute
  '/admin/ai-health': typeof AuthenticatedAdminAdminAiHealthRoute
  '/admin/ai-limits': typeof AuthenticatedAdminAdminAiLimitsRoute
  '/admin/ai-logs': typeof AuthenticatedAdminAdminAiLogsRoute
  '/admin/ai-models': typeof AuthenticatedAdminAdminAiModelsRoute
  '/admin/ai-prompts': typeof AuthenticatedAdminAdminAiPromptsRoute
  '/admin/ai-providers': typeof AuthenticatedAdminAdminAiProvidersRoute
  '/admin/ai-routing': typeof AuthenticatedAdminAdminAiRoutingRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/books': typeof AuthenticatedAdminAdminBooksRoute
  '/admin/cache': typeof AuthenticatedAdminAdminCacheRoute
  '/admin/coupons': typeof AuthenticatedAdminAdminCouponsRoute
  '/admin/email-logs': typeof AuthenticatedAdminAdminEmailLogsRoute
  '/admin/email-templates': typeof AuthenticatedAdminAdminEmailTemplatesRoute
  '/admin/messages': typeof AuthenticatedAdminAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/payment-gateways': typeof AuthenticatedAdminAdminPaymentGatewaysRoute
  '/admin/plans': typeof AuthenticatedAdminAdminPlansRoute
  '/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/books/new': typeof AuthenticatedAppBooksNewRoute
  '/checkout/cancel': typeof AuthenticatedAppCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedAppCheckoutSuccessRoute
  '/api/public/blog-images/$': typeof ApiPublicBlogImagesSplatRoute
  '/api/public/webhooks/$gateway': typeof ApiPublicWebhooksGatewayRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/books/': typeof AuthenticatedAppBooksIndexRoute
  '/admin/blog/$postId': typeof AuthenticatedAdminAdminBlogPostIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminAdminBlogNewRoute
  '/books/$bookId/interview': typeof AuthenticatedAppBooksBookIdInterviewRoute
  '/books/$bookId/manuscript': typeof AuthenticatedAppBooksBookIdManuscriptRoute
  '/books/$bookId/photos': typeof AuthenticatedAppBooksBookIdPhotosRoute
  '/books/$bookId/preview': typeof AuthenticatedAppBooksBookIdPreviewRoute
  '/admin/blog/': typeof AuthenticatedAdminAdminBlogIndexRoute
  '/books/$bookId/': typeof AuthenticatedAppBooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof AuthenticatedAppCheckoutRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/orders': typeof AuthenticatedAppOrdersRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/referrals': typeof AuthenticatedAppReferralsRoute
  '/api/public/paypal-callback': typeof ApiPublicPaypalCallbackRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/admin/ai-audit': typeof AuthenticatedAdminAdminAiAuditRoute
  '/admin/ai-costs': typeof AuthenticatedAdminAdminAiCostsRoute
  '/admin/ai-fallback': typeof AuthenticatedAdminAdminAiFallbackRoute
  '/admin/ai-features': typeof AuthenticatedAdminAdminAiFeaturesRoute
  '/admin/ai-health': typeof AuthenticatedAdminAdminAiHealthRoute
  '/admin/ai-limits': typeof AuthenticatedAdminAdminAiLimitsRoute
  '/admin/ai-logs': typeof AuthenticatedAdminAdminAiLogsRoute
  '/admin/ai-models': typeof AuthenticatedAdminAdminAiModelsRoute
  '/admin/ai-prompts': typeof AuthenticatedAdminAdminAiPromptsRoute
  '/admin/ai-providers': typeof AuthenticatedAdminAdminAiProvidersRoute
  '/admin/ai-routing': typeof AuthenticatedAdminAdminAiRoutingRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/books': typeof AuthenticatedAdminAdminBooksRoute
  '/admin/cache': typeof AuthenticatedAdminAdminCacheRoute
  '/admin/coupons': typeof AuthenticatedAdminAdminCouponsRoute
  '/admin/email-logs': typeof AuthenticatedAdminAdminEmailLogsRoute
  '/admin/email-templates': typeof AuthenticatedAdminAdminEmailTemplatesRoute
  '/admin/messages': typeof AuthenticatedAdminAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/payment-gateways': typeof AuthenticatedAdminAdminPaymentGatewaysRoute
  '/admin/plans': typeof AuthenticatedAdminAdminPlansRoute
  '/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/books/new': typeof AuthenticatedAppBooksNewRoute
  '/checkout/cancel': typeof AuthenticatedAppCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedAppCheckoutSuccessRoute
  '/api/public/blog-images/$': typeof ApiPublicBlogImagesSplatRoute
  '/api/public/webhooks/$gateway': typeof ApiPublicWebhooksGatewayRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/books': typeof AuthenticatedAppBooksIndexRoute
  '/admin/blog/$postId': typeof AuthenticatedAdminAdminBlogPostIdRoute
  '/admin/blog/new': typeof AuthenticatedAdminAdminBlogNewRoute
  '/books/$bookId/interview': typeof AuthenticatedAppBooksBookIdInterviewRoute
  '/books/$bookId/manuscript': typeof AuthenticatedAppBooksBookIdManuscriptRoute
  '/books/$bookId/photos': typeof AuthenticatedAppBooksBookIdPhotosRoute
  '/books/$bookId/preview': typeof AuthenticatedAppBooksBookIdPreviewRoute
  '/admin/blog': typeof AuthenticatedAdminAdminBlogIndexRoute
  '/books/$bookId': typeof AuthenticatedAppBooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/_app/checkout': typeof AuthenticatedAppCheckoutRouteWithChildren
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/referrals': typeof AuthenticatedAppReferralsRoute
  '/api/public/paypal-callback': typeof ApiPublicPaypalCallbackRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/_authenticated/_admin/admin/ai-audit': typeof AuthenticatedAdminAdminAiAuditRoute
  '/_authenticated/_admin/admin/ai-costs': typeof AuthenticatedAdminAdminAiCostsRoute
  '/_authenticated/_admin/admin/ai-fallback': typeof AuthenticatedAdminAdminAiFallbackRoute
  '/_authenticated/_admin/admin/ai-features': typeof AuthenticatedAdminAdminAiFeaturesRoute
  '/_authenticated/_admin/admin/ai-health': typeof AuthenticatedAdminAdminAiHealthRoute
  '/_authenticated/_admin/admin/ai-limits': typeof AuthenticatedAdminAdminAiLimitsRoute
  '/_authenticated/_admin/admin/ai-logs': typeof AuthenticatedAdminAdminAiLogsRoute
  '/_authenticated/_admin/admin/ai-models': typeof AuthenticatedAdminAdminAiModelsRoute
  '/_authenticated/_admin/admin/ai-prompts': typeof AuthenticatedAdminAdminAiPromptsRoute
  '/_authenticated/_admin/admin/ai-providers': typeof AuthenticatedAdminAdminAiProvidersRoute
  '/_authenticated/_admin/admin/ai-routing': typeof AuthenticatedAdminAdminAiRoutingRoute
  '/_authenticated/_admin/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/_authenticated/_admin/admin/books': typeof AuthenticatedAdminAdminBooksRoute
  '/_authenticated/_admin/admin/cache': typeof AuthenticatedAdminAdminCacheRoute
  '/_authenticated/_admin/admin/coupons': typeof AuthenticatedAdminAdminCouponsRoute
  '/_authenticated/_admin/admin/email-logs': typeof AuthenticatedAdminAdminEmailLogsRoute
  '/_authenticated/_admin/admin/email-templates': typeof AuthenticatedAdminAdminEmailTemplatesRoute
  '/_authenticated/_admin/admin/messages': typeof AuthenticatedAdminAdminMessagesRoute
  '/_authenticated/_admin/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/_authenticated/_admin/admin/payment-gateways': typeof AuthenticatedAdminAdminPaymentGatewaysRoute
  '/_authenticated/_admin/admin/plans': typeof AuthenticatedAdminAdminPlansRoute
  '/_authenticated/_admin/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_app/books/new': typeof AuthenticatedAppBooksNewRoute
  '/_authenticated/_app/checkout/cancel': typeof AuthenticatedAppCheckoutCancelRoute
  '/_authenticated/_app/checkout/success': typeof AuthenticatedAppCheckoutSuccessRoute
  '/api/public/blog-images/$': typeof ApiPublicBlogImagesSplatRoute
  '/api/public/webhooks/$gateway': typeof ApiPublicWebhooksGatewayRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_app/books/': typeof AuthenticatedAppBooksIndexRoute
  '/_authenticated/_admin/admin/blog/$postId': typeof AuthenticatedAdminAdminBlogPostIdRoute
  '/_authenticated/_admin/admin/blog/new': typeof AuthenticatedAdminAdminBlogNewRoute
  '/_authenticated/_app/books/$bookId/interview': typeof AuthenticatedAppBooksBookIdInterviewRoute
  '/_authenticated/_app/books/$bookId/manuscript': typeof AuthenticatedAppBooksBookIdManuscriptRoute
  '/_authenticated/_app/books/$bookId/photos': typeof AuthenticatedAppBooksBookIdPhotosRoute
  '/_authenticated/_app/books/$bookId/preview': typeof AuthenticatedAppBooksBookIdPreviewRoute
  '/_authenticated/_admin/admin/blog/': typeof AuthenticatedAdminAdminBlogIndexRoute
  '/_authenticated/_app/books/$bookId/': typeof AuthenticatedAppBooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/referrals'
    | '/api/public/paypal-callback'
    | '/api/public/settings'
    | '/admin/ai-audit'
    | '/admin/ai-costs'
    | '/admin/ai-fallback'
    | '/admin/ai-features'
    | '/admin/ai-health'
    | '/admin/ai-limits'
    | '/admin/ai-logs'
    | '/admin/ai-models'
    | '/admin/ai-prompts'
    | '/admin/ai-providers'
    | '/admin/ai-routing'
    | '/admin/analytics'
    | '/admin/books'
    | '/admin/cache'
    | '/admin/coupons'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payment-gateways'
    | '/admin/plans'
    | '/admin/referrals'
    | '/admin/settings'
    | '/admin/users'
    | '/books/new'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/api/public/blog-images/$'
    | '/api/public/webhooks/$gateway'
    | '/admin/'
    | '/books/'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/books/$bookId/interview'
    | '/books/$bookId/manuscript'
    | '/books/$bookId/photos'
    | '/books/$bookId/preview'
    | '/admin/blog/'
    | '/books/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/referrals'
    | '/api/public/paypal-callback'
    | '/api/public/settings'
    | '/admin/ai-audit'
    | '/admin/ai-costs'
    | '/admin/ai-fallback'
    | '/admin/ai-features'
    | '/admin/ai-health'
    | '/admin/ai-limits'
    | '/admin/ai-logs'
    | '/admin/ai-models'
    | '/admin/ai-prompts'
    | '/admin/ai-providers'
    | '/admin/ai-routing'
    | '/admin/analytics'
    | '/admin/books'
    | '/admin/cache'
    | '/admin/coupons'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payment-gateways'
    | '/admin/plans'
    | '/admin/referrals'
    | '/admin/settings'
    | '/admin/users'
    | '/books/new'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/api/public/blog-images/$'
    | '/api/public/webhooks/$gateway'
    | '/admin'
    | '/books'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/books/$bookId/interview'
    | '/books/$bookId/manuscript'
    | '/books/$bookId/photos'
    | '/books/$bookId/preview'
    | '/admin/blog'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/_admin'
    | '/_authenticated/_app'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/_app/checkout'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/orders'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/referrals'
    | '/api/public/paypal-callback'
    | '/api/public/settings'
    | '/_authenticated/_admin/admin/ai-audit'
    | '/_authenticated/_admin/admin/ai-costs'
    | '/_authenticated/_admin/admin/ai-fallback'
    | '/_authenticated/_admin/admin/ai-features'
    | '/_authenticated/_admin/admin/ai-health'
    | '/_authenticated/_admin/admin/ai-limits'
    | '/_authenticated/_admin/admin/ai-logs'
    | '/_authenticated/_admin/admin/ai-models'
    | '/_authenticated/_admin/admin/ai-prompts'
    | '/_authenticated/_admin/admin/ai-providers'
    | '/_authenticated/_admin/admin/ai-routing'
    | '/_authenticated/_admin/admin/analytics'
    | '/_authenticated/_admin/admin/books'
    | '/_authenticated/_admin/admin/cache'
    | '/_authenticated/_admin/admin/coupons'
    | '/_authenticated/_admin/admin/email-logs'
    | '/_authenticated/_admin/admin/email-templates'
    | '/_authenticated/_admin/admin/messages'
    | '/_authenticated/_admin/admin/orders'
    | '/_authenticated/_admin/admin/payment-gateways'
    | '/_authenticated/_admin/admin/plans'
    | '/_authenticated/_admin/admin/referrals'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_app/books/new'
    | '/_authenticated/_app/checkout/cancel'
    | '/_authenticated/_app/checkout/success'
    | '/api/public/blog-images/$'
    | '/api/public/webhooks/$gateway'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_app/books/'
    | '/_authenticated/_admin/admin/blog/$postId'
    | '/_authenticated/_admin/admin/blog/new'
    | '/_authenticated/_app/books/$bookId/interview'
    | '/_authenticated/_app/books/$bookId/manuscript'
    | '/_authenticated/_app/books/$bookId/photos'
    | '/_authenticated/_app/books/$bookId/preview'
    | '/_authenticated/_admin/admin/blog/'
    | '/_authenticated/_app/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicPaypalCallbackRoute: typeof ApiPublicPaypalCallbackRoute
  ApiPublicSettingsRoute: typeof ApiPublicSettingsRoute
  ApiPublicBlogImagesSplatRoute: typeof ApiPublicBlogImagesSplatRoute
  ApiPublicWebhooksGatewayRoute: typeof ApiPublicWebhooksGatewayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/settings': {
      id: '/api/public/settings'
      path: '/api/public/settings'
      fullPath: '/api/public/settings'
      preLoaderRoute: typeof ApiPublicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-callback': {
      id: '/api/public/paypal-callback'
      path: '/api/public/paypal-callback'
      fullPath: '/api/public/paypal-callback'
      preLoaderRoute: typeof ApiPublicPaypalCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/referrals': {
      id: '/_authenticated/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/orders': {
      id: '/_authenticated/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/checkout': {
      id: '/_authenticated/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedAppCheckoutRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/books/': {
      id: '/_authenticated/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AuthenticatedAppBooksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/$gateway': {
      id: '/api/public/webhooks/$gateway'
      path: '/api/public/webhooks/$gateway'
      fullPath: '/api/public/webhooks/$gateway'
      preLoaderRoute: typeof ApiPublicWebhooksGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog-images/$': {
      id: '/api/public/blog-images/$'
      path: '/api/public/blog-images/$'
      fullPath: '/api/public/blog-images/$'
      preLoaderRoute: typeof ApiPublicBlogImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/checkout/success': {
      id: '/_authenticated/_app/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedAppCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedAppCheckoutRoute
    }
    '/_authenticated/_app/checkout/cancel': {
      id: '/_authenticated/_app/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof AuthenticatedAppCheckoutCancelRouteImport
      parentRoute: typeof AuthenticatedAppCheckoutRoute
    }
    '/_authenticated/_app/books/new': {
      id: '/_authenticated/_app/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedAppBooksNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/referrals': {
      id: '/_authenticated/_admin/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/plans': {
      id: '/_authenticated/_admin/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/payment-gateways': {
      id: '/_authenticated/_admin/admin/payment-gateways'
      path: '/admin/payment-gateways'
      fullPath: '/admin/payment-gateways'
      preLoaderRoute: typeof AuthenticatedAdminAdminPaymentGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/orders': {
      id: '/_authenticated/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/messages': {
      id: '/_authenticated/_admin/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/email-templates': {
      id: '/_authenticated/_admin/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/email-logs': {
      id: '/_authenticated/_admin/admin/email-logs'
      path: '/admin/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AuthenticatedAdminAdminEmailLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/coupons': {
      id: '/_authenticated/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/cache': {
      id: '/_authenticated/_admin/admin/cache'
      path: '/admin/cache'
      fullPath: '/admin/cache'
      preLoaderRoute: typeof AuthenticatedAdminAdminCacheRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/books': {
      id: '/_authenticated/_admin/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AuthenticatedAdminAdminBooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/analytics': {
      id: '/_authenticated/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-routing': {
      id: '/_authenticated/_admin/admin/ai-routing'
      path: '/admin/ai-routing'
      fullPath: '/admin/ai-routing'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiRoutingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-providers': {
      id: '/_authenticated/_admin/admin/ai-providers'
      path: '/admin/ai-providers'
      fullPath: '/admin/ai-providers'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-prompts': {
      id: '/_authenticated/_admin/admin/ai-prompts'
      path: '/admin/ai-prompts'
      fullPath: '/admin/ai-prompts'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiPromptsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-models': {
      id: '/_authenticated/_admin/admin/ai-models'
      path: '/admin/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiModelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-logs': {
      id: '/_authenticated/_admin/admin/ai-logs'
      path: '/admin/ai-logs'
      fullPath: '/admin/ai-logs'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-limits': {
      id: '/_authenticated/_admin/admin/ai-limits'
      path: '/admin/ai-limits'
      fullPath: '/admin/ai-limits'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiLimitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-health': {
      id: '/_authenticated/_admin/admin/ai-health'
      path: '/admin/ai-health'
      fullPath: '/admin/ai-health'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-features': {
      id: '/_authenticated/_admin/admin/ai-features'
      path: '/admin/ai-features'
      fullPath: '/admin/ai-features'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiFeaturesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-fallback': {
      id: '/_authenticated/_admin/admin/ai-fallback'
      path: '/admin/ai-fallback'
      fullPath: '/admin/ai-fallback'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiFallbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-costs': {
      id: '/_authenticated/_admin/admin/ai-costs'
      path: '/admin/ai-costs'
      fullPath: '/admin/ai-costs'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiCostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai-audit': {
      id: '/_authenticated/_admin/admin/ai-audit'
      path: '/admin/ai-audit'
      fullPath: '/admin/ai-audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_app/books/$bookId/': {
      id: '/_authenticated/_app/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof AuthenticatedAppBooksBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/blog/': {
      id: '/_authenticated/_admin/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_app/books/$bookId/preview': {
      id: '/_authenticated/_app/books/$bookId/preview'
      path: '/books/$bookId/preview'
      fullPath: '/books/$bookId/preview'
      preLoaderRoute: typeof AuthenticatedAppBooksBookIdPreviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/books/$bookId/photos': {
      id: '/_authenticated/_app/books/$bookId/photos'
      path: '/books/$bookId/photos'
      fullPath: '/books/$bookId/photos'
      preLoaderRoute: typeof AuthenticatedAppBooksBookIdPhotosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/books/$bookId/manuscript': {
      id: '/_authenticated/_app/books/$bookId/manuscript'
      path: '/books/$bookId/manuscript'
      fullPath: '/books/$bookId/manuscript'
      preLoaderRoute: typeof AuthenticatedAppBooksBookIdManuscriptRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/books/$bookId/interview': {
      id: '/_authenticated/_app/books/$bookId/interview'
      path: '/books/$bookId/interview'
      fullPath: '/books/$bookId/interview'
      preLoaderRoute: typeof AuthenticatedAppBooksBookIdInterviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/blog/new': {
      id: '/_authenticated/_admin/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/blog/$postId': {
      id: '/_authenticated/_admin/admin/blog/$postId'
      path: '/admin/blog/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AuthenticatedAdminAdminBlogPostIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAiAuditRoute: typeof AuthenticatedAdminAdminAiAuditRoute
  AuthenticatedAdminAdminAiCostsRoute: typeof AuthenticatedAdminAdminAiCostsRoute
  AuthenticatedAdminAdminAiFallbackRoute: typeof AuthenticatedAdminAdminAiFallbackRoute
  AuthenticatedAdminAdminAiFeaturesRoute: typeof AuthenticatedAdminAdminAiFeaturesRoute
  AuthenticatedAdminAdminAiHealthRoute: typeof AuthenticatedAdminAdminAiHealthRoute
  AuthenticatedAdminAdminAiLimitsRoute: typeof AuthenticatedAdminAdminAiLimitsRoute
  AuthenticatedAdminAdminAiLogsRoute: typeof AuthenticatedAdminAdminAiLogsRoute
  AuthenticatedAdminAdminAiModelsRoute: typeof AuthenticatedAdminAdminAiModelsRoute
  AuthenticatedAdminAdminAiPromptsRoute: typeof AuthenticatedAdminAdminAiPromptsRoute
  AuthenticatedAdminAdminAiProvidersRoute: typeof AuthenticatedAdminAdminAiProvidersRoute
  AuthenticatedAdminAdminAiRoutingRoute: typeof AuthenticatedAdminAdminAiRoutingRoute
  AuthenticatedAdminAdminAnalyticsRoute: typeof AuthenticatedAdminAdminAnalyticsRoute
  AuthenticatedAdminAdminBooksRoute: typeof AuthenticatedAdminAdminBooksRoute
  AuthenticatedAdminAdminCacheRoute: typeof AuthenticatedAdminAdminCacheRoute
  AuthenticatedAdminAdminCouponsRoute: typeof AuthenticatedAdminAdminCouponsRoute
  AuthenticatedAdminAdminEmailLogsRoute: typeof AuthenticatedAdminAdminEmailLogsRoute
  AuthenticatedAdminAdminEmailTemplatesRoute: typeof AuthenticatedAdminAdminEmailTemplatesRoute
  AuthenticatedAdminAdminMessagesRoute: typeof AuthenticatedAdminAdminMessagesRoute
  AuthenticatedAdminAdminOrdersRoute: typeof AuthenticatedAdminAdminOrdersRoute
  AuthenticatedAdminAdminPaymentGatewaysRoute: typeof AuthenticatedAdminAdminPaymentGatewaysRoute
  AuthenticatedAdminAdminPlansRoute: typeof AuthenticatedAdminAdminPlansRoute
  AuthenticatedAdminAdminReferralsRoute: typeof AuthenticatedAdminAdminReferralsRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminBlogPostIdRoute: typeof AuthenticatedAdminAdminBlogPostIdRoute
  AuthenticatedAdminAdminBlogNewRoute: typeof AuthenticatedAdminAdminBlogNewRoute
  AuthenticatedAdminAdminBlogIndexRoute: typeof AuthenticatedAdminAdminBlogIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAiAuditRoute: AuthenticatedAdminAdminAiAuditRoute,
  AuthenticatedAdminAdminAiCostsRoute: AuthenticatedAdminAdminAiCostsRoute,
  AuthenticatedAdminAdminAiFallbackRoute:
    AuthenticatedAdminAdminAiFallbackRoute,
  AuthenticatedAdminAdminAiFeaturesRoute:
    AuthenticatedAdminAdminAiFeaturesRoute,
  AuthenticatedAdminAdminAiHealthRoute: AuthenticatedAdminAdminAiHealthRoute,
  AuthenticatedAdminAdminAiLimitsRoute: AuthenticatedAdminAdminAiLimitsRoute,
  AuthenticatedAdminAdminAiLogsRoute: AuthenticatedAdminAdminAiLogsRoute,
  AuthenticatedAdminAdminAiModelsRoute: AuthenticatedAdminAdminAiModelsRoute,
  AuthenticatedAdminAdminAiPromptsRoute: AuthenticatedAdminAdminAiPromptsRoute,
  AuthenticatedAdminAdminAiProvidersRoute:
    AuthenticatedAdminAdminAiProvidersRoute,
  AuthenticatedAdminAdminAiRoutingRoute: AuthenticatedAdminAdminAiRoutingRoute,
  AuthenticatedAdminAdminAnalyticsRoute: AuthenticatedAdminAdminAnalyticsRoute,
  AuthenticatedAdminAdminBooksRoute: AuthenticatedAdminAdminBooksRoute,
  AuthenticatedAdminAdminCacheRoute: AuthenticatedAdminAdminCacheRoute,
  AuthenticatedAdminAdminCouponsRoute: AuthenticatedAdminAdminCouponsRoute,
  AuthenticatedAdminAdminEmailLogsRoute: AuthenticatedAdminAdminEmailLogsRoute,
  AuthenticatedAdminAdminEmailTemplatesRoute:
    AuthenticatedAdminAdminEmailTemplatesRoute,
  AuthenticatedAdminAdminMessagesRoute: AuthenticatedAdminAdminMessagesRoute,
  AuthenticatedAdminAdminOrdersRoute: AuthenticatedAdminAdminOrdersRoute,
  AuthenticatedAdminAdminPaymentGatewaysRoute:
    AuthenticatedAdminAdminPaymentGatewaysRoute,
  AuthenticatedAdminAdminPlansRoute: AuthenticatedAdminAdminPlansRoute,
  AuthenticatedAdminAdminReferralsRoute: AuthenticatedAdminAdminReferralsRoute,
  AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  AuthenticatedAdminAdminBlogPostIdRoute:
    AuthenticatedAdminAdminBlogPostIdRoute,
  AuthenticatedAdminAdminBlogNewRoute: AuthenticatedAdminAdminBlogNewRoute,
  AuthenticatedAdminAdminBlogIndexRoute: AuthenticatedAdminAdminBlogIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppCheckoutRouteChildren {
  AuthenticatedAppCheckoutCancelRoute: typeof AuthenticatedAppCheckoutCancelRoute
  AuthenticatedAppCheckoutSuccessRoute: typeof AuthenticatedAppCheckoutSuccessRoute
}

const AuthenticatedAppCheckoutRouteChildren: AuthenticatedAppCheckoutRouteChildren =
  {
    AuthenticatedAppCheckoutCancelRoute: AuthenticatedAppCheckoutCancelRoute,
    AuthenticatedAppCheckoutSuccessRoute: AuthenticatedAppCheckoutSuccessRoute,
  }

const AuthenticatedAppCheckoutRouteWithChildren =
  AuthenticatedAppCheckoutRoute._addFileChildren(
    AuthenticatedAppCheckoutRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCheckoutRoute: typeof AuthenticatedAppCheckoutRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppBooksNewRoute: typeof AuthenticatedAppBooksNewRoute
  AuthenticatedAppBooksIndexRoute: typeof AuthenticatedAppBooksIndexRoute
  AuthenticatedAppBooksBookIdInterviewRoute: typeof AuthenticatedAppBooksBookIdInterviewRoute
  AuthenticatedAppBooksBookIdManuscriptRoute: typeof AuthenticatedAppBooksBookIdManuscriptRoute
  AuthenticatedAppBooksBookIdPhotosRoute: typeof AuthenticatedAppBooksBookIdPhotosRoute
  AuthenticatedAppBooksBookIdPreviewRoute: typeof AuthenticatedAppBooksBookIdPreviewRoute
  AuthenticatedAppBooksBookIdIndexRoute: typeof AuthenticatedAppBooksBookIdIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCheckoutRoute: AuthenticatedAppCheckoutRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppBooksNewRoute: AuthenticatedAppBooksNewRoute,
  AuthenticatedAppBooksIndexRoute: AuthenticatedAppBooksIndexRoute,
  AuthenticatedAppBooksBookIdInterviewRoute:
    AuthenticatedAppBooksBookIdInterviewRoute,
  AuthenticatedAppBooksBookIdManuscriptRoute:
    AuthenticatedAppBooksBookIdManuscriptRoute,
  AuthenticatedAppBooksBookIdPhotosRoute:
    AuthenticatedAppBooksBookIdPhotosRoute,
  AuthenticatedAppBooksBookIdPreviewRoute:
    AuthenticatedAppBooksBookIdPreviewRoute,
  AuthenticatedAppBooksBookIdIndexRoute: AuthenticatedAppBooksBookIdIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicPaypalCallbackRoute: ApiPublicPaypalCallbackRoute,
  ApiPublicSettingsRoute: ApiPublicSettingsRoute,
  ApiPublicBlogImagesSplatRoute: ApiPublicBlogImagesSplatRoute,
  ApiPublicWebhooksGatewayRoute: ApiPublicWebhooksGatewayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
